//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etec.HardTechnologies.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINALIZAR_SERVICO
    {
        public int IDFINALIZACAO { get; set; }
        public int IDSERVICO { get; set; }
        public string RELATORIO { get; set; }
        public Nullable<System.DateTime> DTENCERRAMENTO { get; set; }
        public int IDEQUIPE { get; set; }
        public string FORMAPAGAMENTO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<bool> PAGO { get; set; }
    
        public virtual SERVICO SERVICO { get; set; }
    }
}
