//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etec.HardTechnologies.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICO()
        {
            this.FINALIZAR_SERVICO = new HashSet<FINALIZAR_SERVICO>();
        }
    
        public int IDSERVICO { get; set; }
        public System.DateTime DTABERTURA { get; set; }
        public System.TimeSpan HORARIO { get; set; }
        public System.DateTime DTVENCIMENTO { get; set; }
        public int IDFINALIDADE { get; set; }
        public int IDCATEGORIA { get; set; }
        public string ELEMENTO { get; set; }
        public string URGENCIA { get; set; }
        public string IMPACTO { get; set; }
        public string PROBLEMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINALIZAR_SERVICO> FINALIZAR_SERVICO { get; set; }
    }
}
