--CRIAÇÃO DO BANCO
CREATE DATABASE GenesysDB
GO

--USAR O BANCO
USE GenesysDB
GO

--CRIAÇÃO DE TABELAS

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY IDENTITY,
RAZAO VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
CNPJ VARCHAR(20) UNIQUE NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR(10),
CEP VARCHAR(9) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
ESTADO CHAR(2) NOT NULL,
TELEFONE VARCHAR(25) NOT NULL,
CELULAR VARCHAR(25) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
WEBSITE VARCHAR(40) NOT NULL
)
GO


CREATE TABLE TURNO_DIA(
IDDIA INT PRIMARY KEY IDENTITY,
DIA VARCHAR(15) NOT NULL
)
GO

CREATE TABLE TURNO_PERIODO(
IDPERIODO INT PRIMARY KEY IDENTITY,
PERIODO VARCHAR(15) NOT NULL
)
GO

CREATE TABLE FUNCIONARIO(
IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL,
CPF VARCHAR(20) UNIQUE NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR(10),
CEP VARCHAR(9) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
ESTADO CHAR(2) NOT NULL,
TELEFONE VARCHAR(25) NOT NULL,
CELULAR VARCHAR(25) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
CARGO VARCHAR(25) NOT NULL
)
GO

CREATE TABLE FUNCIONARIO_TURNO(
IDFUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIO(IDFUNCIONARIO) NOT NULL,
IDDIA INT FOREIGN KEY REFERENCES TURNO_DIA(IDDIA) NOT NULL,
IDPERIODO INT FOREIGN KEY REFERENCES TURNO_PERIODO(IDPERIODO) NOT NULL
)
GO

CREATE TABLE FORNECEDOR(
IDFORNECEDOR INT PRIMARY KEY IDENTITY,
RAZAO VARCHAR(30) NOT NULL,
NOME VARCHAR(30) NOT NULL,
CNPJ VARCHAR(20) UNIQUE NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
NUMERO INT NOT NULL,
COMPLEMENTO VARCHAR(10),
CEP VARCHAR(10) NOT NULL,
BAIRRO VARCHAR(20) NOT NULL,
CIDADE VARCHAR(20) NOT NULL,
ESTADO CHAR(2) NOT NULL,
TELEFONE VARCHAR(25) NOT NULL,
CELULAR VARCHAR(25) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
WEBSITE VARCHAR(40) NOT NULL
)
GO

CREATE TABLE LOGIN_USUARIO(
IDLOGIN INT PRIMARY KEY IDENTITY,
USUARIO VARCHAR(20) UNIQUE NOT NULL,
SENHA INT NOT NULL,
NIVEL VARCHAR(25) NOT NULL,
CLIENTE VARCHAR(40),
FORNECEDOR VARCHAR(40)
)
GO

CREATE TABLE EQUIPAMENTO(
IDEQUIPAMENTO INT PRIMARY KEY IDENTITY,
NOME VARCHAR(25) NOT NULL,
FABRICACAO VARCHAR(10) NOT NULL,
MODELO VARCHAR(15) NOT NULL,
NUMEROSERIE VARCHAR(20) NOT NULL,
VLCOMPRA MONEY NOT NULL,
MARCA VARCHAR(20) NOT NULL,
ESTOQUE INT
)
GO

CREATE TABLE FORNECEDOR_EQUIPAMENTO(
IDFORNECEDOR INT FOREIGN KEY REFERENCES FORNECEDOR(IDFORNECEDOR) NOT NULL,
IDEQUIPAMENTO INT FOREIGN KEY REFERENCES EQUIPAMENTO(IDEQUIPAMENTO) NOT NULL,
)
GO

CREATE TABLE EQUIPAMENTO_CLIENTE(
IDEQUIPAMENTO INT FOREIGN KEY REFERENCES EQUIPAMENTO(IDEQUIPAMENTO) NOT NULL,
DTALUGUEL DATE NOT NULL,
VLALUGUEL MONEY NOT NULL,
IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE) NOT NULL
)
GO

CREATE TABLE SERVICO(
IDSERVICO INT PRIMARY KEY IDENTITY,
DTABERTURA DATE NOT NULL,
HORARIO TIME NOT NULL,
DTVENCIMENTO DATE NOT NULL,
FINALIDADE VARCHAR(20) NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL,
ELEMENTO VARCHAR(30),
URGENCIA VARCHAR(10) NOT NULL,
IMPACTO VARCHAR(10) NOT NULL,
PROBLEMA VARCHAR(100)NOT NULL,
)
GO

CREATE TABLE SERVICO_CLIENTE(
IDSERVICO INT FOREIGN KEY REFERENCES SERVICO(IDSERVICO),
IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTE(IDCLIENTE)
)
GO

CREATE TABLE FINALIZAR_SERVICO(
IDFINALIZACAO INT PRIMARY KEY IDENTITY,
IDSERVICO INT FOREIGN KEY REFERENCES SERVICO(IDSERVICO) UNIQUE NOT NULL,
RELATORIO VARCHAR(100) NOT NULL,
DTENCERRAMENTO DATE,
FORMAPAGAMENTO VARCHAR(15),
VALOR MONEY,
GASTOS MONEY,
PAGO BIT
)
GO

CREATE TABLE AGENDA(
IDAGENDA INT PRIMARY KEY IDENTITY NOT NULL,
LOCAL VARCHAR(40) NOT NULL,
DATA DATE NOT NULL,
HORARIO TIME,
FUNCIONARIO VARCHAR(50)
)
GO

-- SELECT'S

SELECT * FROM CLIENTE
SELECT * FROM TURNO_DIA
SELECT * FROM TURNO_PERIODO
SELECT * FROM CARGO
SELECT * FROM FUNCIONARIO
SELECT * FROM FUNCIONARIO_TURNO
SELECT * FROM EQUIPE
SELECT * FROM FORNECEDOR
SELECT * FROM MARCA
SELECT * FROM EQUIPAMENTO
SELECT * FROM FORNECEDOR_EQUIPAMENTO
SELECT * FROM EQUIPAMENTO_CLIENTE
SELECT * FROM FINALIDADE
SELECT * FROM CATEGORIA
SELECT * FROM SERVICO
SELECT * FROM SERVICO_CLIENTE
SELECT * FROM FINALIZAR_SERVICO
SELECT * FROM LOGIN_USUARIO
GO

-- INSERT INTO CLIENTE
SELECT * FROM CLIENTE
INSERT INTO CLIENTE VALUES('Algar Telecomunicações', 'Algar Telecom', '03928194500001', 'Av. Consolação', '295', 'Cj 14', '123455', 'Leopoldina', 'São Paulo', 'SP', '551183746589', '5511923950187', 'algartelecom@gmail.com', 'www.algar.com.br')
INSERT INTO CLIENTE VALUES('Hauwei', 'Hauwei e Serviços', '03928194500002', 'Av. Faria Lima', '395', 'Cj 15', '453567', 'Pirituba', 'São Paulo', 'SP', '551182938495', '5511923950187', 'hauweitelecom@gmail.com', 'www.hawuei.com.br')
INSERT INTO CLIENTE VALUES('VIVO', 'Vivo Telefônica', '03928194500003', 'Av. Auutonomistas', '495', 'Cj 16', '054589', 'Tijuca', 'Rio de Janeiro', 'RJ', '551137484028', '5511923950187', 'vivotelecom@gmail.com', 'www.vivo.com.br')
INSERT INTO CLIENTE VALUES('TIM', 'Tim Telefone LTDA.', '03928194500004', 'Av. Guaipa', '595', 'Cj 20', '198237', 'Munhoz', 'Osasco', 'SP', '551137484028', '5511923950187', 'timtelecom@gmail.com', 'www.tim.com.br')
GO

--INSERT INTO FORNECEDOR
SELECT * FROM FORNECEDOR
INSERT INTO FORNECEDOR (RAZAO,NOME,CNPJ,ENDERECO,NUMERO,CEP,BAIRRO, CIDADE,ESTADO,TELEFONE,CELULAR,EMAIL,WEBSITE)
VALUES ('Microsoft International Ltda.', 'Microsoft', '102849200001', 'Av. dos Autonomistas', 1, '04829289', 'Centro', 'Osasco', 'SP', '551120345678', '5511937648214', 'microsoftsuporte@hotmail.com', 'www.microsoft.com')
INSERT INTO FORNECEDOR (RAZAO,NOME,CNPJ,ENDERECO,NUMERO,CEP,BAIRRO, CIDADE,ESTADO,TELEFONE,CELULAR,EMAIL,WEBSITE)
VALUES ('Kingstone pen drives Ltda.', 'Kingstone', '2132981200001', 'Av. United Kington', 65, '859470', 'Brooklin', 'New York', 'NY',  '52225869056', '52224859609', 'kingstonseller@outlook.com', 'www.microsoft.com')
GO

-- INSERT INTO LOGIN_USUARIO
SELECT * FROM LOGIN_USUARIO
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL) VALUES ('AILTON', '123456', 'Gerente')
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL) VALUES ('EMERSON', '123456', 'Funcionario')
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL) VALUES ('GERENTE', '123456', 'Gerente')
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL) VALUES ('FUNCIONARIO', '123456', 'Funcionario')
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL,CLIENTE) VALUES ('FORNECEDOR', '123456', 'Fornecedor', 'Microsoft')
INSERT INTO LOGIN_USUARIO (USUARIO,SENHA,NIVEL,FORNECEDOR) VALUES ('CLIENTE', '123456', 'Cliente', 'Carlos Henrique')
GO

-- INSERT INTO SERVICO
SELECT * FROM SERVICO
INSERT INTO SERVICO VALUES ('171005', '19:00', '171105', 'Instalação', 'Software', 'Chefia', '2 - Média', '3 - Baixo', 'Solicito que seja instalado uma rede de internet')
INSERT INTO SERVICO VALUES ('171010', '22:00', '171110', 'Instalação', 'Hardware', 'LG0400', '1 - Alta', '2 - Média', 'Solicito que seja feito a instalação do Notebook')
INSERT INTO SERVICO VALUES ('171015', '06:00', '171115', 'Manutenção', 'Computador', 'SwitchDNS', '3 - Baixo', '3 - Baixo', 'Solicito que seja feito a manutenção do Switch')
INSERT INTO SERVICO VALUES ('171015', '06:00', '171115', 'Manutenção', 'Computador', 'SwitchDNS', '3 - Baixo', '3 - Baixo', 'Solicito que seja feito a manutenção do Switch')
INSERT INTO SERVICO VALUES ('171015', '06:00', '171115', 'Remoção', 'Software', 'UPLINK', '3 - Alto', '3 - Alto', 'Solicito que seja feito a remoção do UPLINK')
GO

-- INSERT INTO SERVICO_CLIENTE
SELECT * FROM SERVICO_CLIENTE
INSERT INTO SERVICO_CLIENTE VALUES (1,1)
INSERT INTO SERVICO_CLIENTE VALUES (2,2)
INSERT INTO SERVICO_CLIENTE VALUES (3,3)
INSERT INTO SERVICO_CLIENTE VALUES (4,1)
INSERT INTO SERVICO_CLIENTE VALUES (2,5)
go


-- INSERT INTO FINALIZAR_SERVICO
SELECT * FROM FINALIZAR_SERVICO
INSERT INTO FINALIZAR_SERVICO VALUES (1, 'Tudo OK', '171030', '3 - Crédito', '220.5', '30.5', 0)
INSERT INTO FINALIZAR_SERVICO VALUES (2, 'Tudo OK', '171030', '2 - Débito', 220.5, 50, 1)
INSERT INTO FINALIZAR_SERVICO VALUES (3, 'Tudo OK', '171030', '1 - Dinheiro', 220.5, 120.5, 1)
GO

--INSERT INTO EQUIPAMENTO
SELECT * FROM EQUIPAMENTO
INSERT INTO EQUIPAMENTO VALUES ('SWITCH', '022017', 'LINKUP234', '1233456789', '99.90', 'Linkdoo', 10)
INSERT INTO EQUIPAMENTO VALUES ('Pen Drive', '102017', 'Travaler20', '987654321', '20.50', 'Travalando', 40)
INSERT INTO EQUIPAMENTO VALUES ('HD', '102017', 'Travaler20', '987654321', '40.50', 'Travalando', 20)
INSERT INTO EQUIPAMENTO VALUES ('Roteador', '102017', 'Travaler20', '987654321', '100.50', 'Travalando', 5)
GO

--INSERT INTO FORNECEDOR_EQUIPAMENTO
SELECT * FROM FORNECEDOR_EQUIPAMENTO
INSERT INTO FORNECEDOR_EQUIPAMENTO VALUES (1,1)
INSERT INTO FORNECEDOR_EQUIPAMENTO VALUES (2,2)
GO


--INSERT INTO EQUIPAMENTO CLIENTE
SELECT * FROM EQUIPAMENTO_CLIENTE
INSERT INTO EQUIPAMENTO_CLIENTE VALUES (1, '010413', 50, 1)
INSERT INTO EQUIPAMENTO_CLIENTE VALUES (2, '131001', 65, 2)
GO

-- INSERT INTO FUNCIONARIO
SELECT * FROM FUNCIONARIO
INSERT INTO FUNCIONARIO VALUES ('Carlos Henrique', '10284920912', 'R. Tito', 475, 'Casa 2', '05923032', 'Vila Ipojuca', 'São Paulo', 'SP', '551148593067', '5511948206789', 'carlos.henrique@hotmail.com', '0 - Diretor')
INSERT INTO FUNCIONARIO VALUES ('Maria Joaquina', '10284920934', 'R. Dinieper', 2, 'Casa 4', '1231241', 'Tijuca', 'Rio de Janeiro', 'RJ', '551148593068', '55119482047', 'maria.prazeres@hotmail.com', '1 - Coordenador')
INSERT INTO FUNCIONARIO VALUES ('João Henrique', '10284920952', 'R. Ponta Pora', 3, 'Apto 2', '4353453', 'Novo Horizonte', 'Belo Horizonte', 'MG', '55114893067', '55119482089', 'joao.baptista@hotmail.com', '2 - Supervisor')
INSERT INTO FUNCIONARIO VALUES ('Wellingtom Medeiros', '10284922312', 'R. Aurelia', 5, '', '3453454', 'Consolação', 'São Paulo', 'SP', '551148593057', '551194820678', 'wellingtom.medeiros@hotmail.com', '4 - Auxiliar')
GO

-- INSERT INTO TURNO_DIA
SELECT * FROM TURNO_DIA
INSERT INTO TURNO_DIA VALUES ('Domingo')
INSERT INTO TURNO_DIA VALUES ('Segunda-Feira')
INSERT INTO TURNO_DIA VALUES ('Terça-Feira')
INSERT INTO TURNO_DIA VALUES ('Quarta-Feira')
INSERT INTO TURNO_DIA VALUES ('Quinta-Feira')
INSERT INTO TURNO_DIA VALUES ('Sexta-Feira')
INSERT INTO TURNO_DIA VALUES ('Sábado')
GO

-- INSERT INTO TURNO_PERIODO
SELECT * FROM TURNO_PERIODO
INSERT INTO TURNO_PERIODO VALUES ('Matutino')
INSERT INTO TURNO_PERIODO VALUES ('Vespertino')
INSERT INTO TURNO_PERIODO VALUES ('Noturno')
INSERT INTO TURNO_PERIODO VALUES ('Diurno')
GO

-- INSERT INTO FUNCIONARIO TURNO
SELECT * FROM FUNCIONARIO_TURNO
INSERT INTO FUNCIONARIO_TURNO VALUES (1,1,2)
INSERT INTO FUNCIONARIO_TURNO VALUES (1,2,3)
INSERT INTO FUNCIONARIO_TURNO VALUES (6,3,4)
INSERT INTO FUNCIONARIO_TURNO VALUES (7,4,1)
INSERT INTO FUNCIONARIO_TURNO VALUES (8,1,3)
GO

-- INSERT INTO AGENDA
select * from agenda
INSERT INTO AGENDA VALUES('Rio de Janeiro', '10/11/2017', '22:20', 'Carlos Henrique')
INSERT INTO AGENDA VALUES('São Paulo', '12/11/2017', '10:20', 'Maria Joaquina')
INSERT INTO AGENDA VALUES('Minas Gerais', '05/12/2017', '02:20', 'João Henrique')
INSERT INTO AGENDA VALUES('Rio de Janeiro', '08/12/2017', '11:20', 'Wellingtom Medeiros')

-- AQUI FICAM AS VIEWS

-- APARECER O NOME DA FINALIDADE E A QTD DE SERVIÇOS

CREATE VIEW [SERVICO POR FINALIDADE]
AS
SELECT COUNT(IDSERVICO) AS 'Nº DE SERVIÇOS', FINALIDADE FROM SERVICO
GROUP BY FINALIDADE
GO

SELECT * FROM [SERVICO POR FINALIDADE]
GO

-- CONTAR QNTOS SERVICOS ABERTOS E FECHADOS

CREATE VIEW [SERVICOS ABERTOS E ENCERRADOS]
AS
SELECT COUNT(SERVICO.IDSERVICO) AS ABERTOS, COUNT(IDFINALIZACAO) AS ENCERRADOS FROM SERVICO
LEFT JOIN FINALIZAR_SERVICO ON SERVICO.IDSERVICO = FINALIZAR_SERVICO.IDSERVICO
GO

SELECT * FROM [SERVICOS ABERTOS E ENCERRADOS]
GO

-- VALORES GANHOS, GASTOS E LUCROS

CREATE VIEW [EXTRATO]
AS
SELECT IDFINALIZACAO AS SERVICO, SUM(VALOR) AS RECEITA, SUM(GASTOS) AS DÉBITO, SUM(VALOR-GASTOS) AS LUCRO FROM FINALIZAR_SERVICO
GROUP BY IDFINALIZACAO
GO

SELECT * FROM EXTRATO
GO

-- 

CREATE VIEW [GANHOS POR FINALIDADE DE SERVIÇO]
AS
SELECT FINALIDADE, SUM(VALOR-GASTOS) AS LUCRO FROM FINALIZAR_SERVICO
INNER JOIN SERVICO
ON SERVICO.IDSERVICO = FINALIZAR_SERVICO.IDSERVICO
GROUP BY FINALIDADE
GO

-- VIEW COM AS INFORMAÇÕES DO SERVICO E FINALIZAR_SERVICO

CREATE VIEW [FINALIZACAO DE SERVICO]
AS
SELECT IDFINALIZACAO, FINALIZAR_SERVICO.IDSERVICO, CLIENTE.NOME, CNPJ, ENDERECO, CIDADE, ESTADO, FINALIDADE, RELATORIO, DTABERTURA ,DTENCERRAMENTO, FORMAPAGAMENTO, VALOR, GASTOS, PAGO FROM FINALIZAR_SERVICO
INNER JOIN SERVICO
ON SERVICO.IDSERVICO = FINALIZAR_SERVICO.IDSERVICO
INNER JOIN SERVICO_CLIENTE
ON SERVICO_CLIENTE.IDSERVICO = SERVICO.IDSERVICO
INNER JOIN CLIENTE
ON SERVICO_CLIENTE.IDCLIENTE = CLIENTE.IDCLIENTE
GO

SELECT * FROM LOGIN_USUARIO

select count(IDLOGIN) AS [Qtd de Usuários], Nivel from LOGIN_USUARIO
group by Nivel


-- NAO UTILIZAR

--CREATE TABLE MARCA(
--IDMARCA INT PRIMARY KEY IDENTITY,
--DESCRICAO VARCHAR(20) NOT NULL,
--)
--GO

--CREATE TABLE CARGO(
--IDCARGO INT PRIMARY KEY IDENTITY,
--NOME VARCHAR(25) UNIQUE
--)
--GO

----INSERT INTO EQUIPE
--SELECT * FROM EQUIPE
--INSERT INTO EQUIPE VALUES (1, 1, 1)
--INSERT INTO EQUIPE VALUES (2, 1, 0)
--INSERT INTO EQUIPE VALUES (3, 1, 0)
--GO

----INSERT INTO MARCA
--SELECT * FROM MARCA
--INSERT INTO MARCA VALUES ('MICROSOFT')
--INSERT INTO MARCA VALUES ('KINGSTONE')
--INSERT INTO MARCA VALUES ('DATA TRAVALER')
--GO

---- INSERT INTO FINALIDADE
--SELECT * FROM FINALIDADE
--INSERT INTO FINALIDADE VALUES ('Manutenção'), ('Instalação'), ('Remoção')
--GO

---- INSERT INTO CATEGORIA
--SELECT * FROM CATEGORIA
--INSERT INTO CATEGORIA VALUES ('Microcomputador'), ('Redes'), ('Equipamento'), ('Software')
--GO

---- INSERT INTO CARGO
--SELECT * FROM CARGO
--INSERT INTO CARGO VALUES ('Técnico de Informática')
--INSERT INTO CARGO VALUES ('Assistente Administrativo')
--INSERT INTO CARGO VALUES ('Recursos Humanos')
--INSERT INTO CARGO VALUES ('Montador')
--INSERT INTO CARGO VALUES ('Telemarketing')
--INSERT INTO CARGO VALUES ('Gerente')
--INSERT INTO CARGO VALUES ('Diretor')
--GO


